# Generated by Django 5.2 on 2025-04-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static/image/subjects/avatar.jpg', upload_to='profiles/'),
        ),
    ]
